<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<title>Installing Windows to System Volume Information  - MyTube</title>
<link href="MyTube.svg" alt="icon">
<link href="style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>MyTube</h1>
<section><button onclick="location.href='https://d292393d-07b9-48bd-97ec-902f153561be-00-w00ru12tawt3.kirk.replit.dev'">Home</button>
<button onclick="location.href='videos.php'">Videos</button></section>
<section>
<video src="uploads/Installing Windows 11 to System Volume Information (720p60, h264, youtube).mp4" controls></video></section>
<h2>Installing Windows to System Volume Information </h2>
<nav>
<section>
<h3>Upload Date: July 10th, 2024</h3>
<h3>Description:</h3>
<p>This message is auto-generated by MyTube.

This video has been ported from YouTube.</p>
<h3>Uploader: Enderman (@endermanch)</h3>
</section>
</nav>
<script src="script.js"></script>
</body>
</html>